# Generated by Django 4.2.1 on 2024-08-21 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='linkeeuser',
            old_name='phone_number',
            new_name='uni_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='location',
        ),
    ]
